bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: twSFKIuyC/aSXfosU2A6kJNHjsmXFvZdw8x+4rIVCetGGRazorf9FgDU/EDe9nl32X7yoMO2nNff36fTLOXrf7VRlYlndK5+5eVPhO3XDR2NL07C0Vv39kXH9mWLnVJ5qNTEtZKyB4H2BkiG+mIf9A3a70gYFe+XHlcMXdER1Dksd93M64FCFJWoiMqTxGex8zizVECAQZQcAlnaKfi0g7cZ/jwyijWkswatfhOjUXQAbIMUdCJM0fRIo7Qcsr3Jv7cpraMVr5/KrutjTq6fx9KLMolGZvIbbkjuw9mHhKpvCTeTB+5AFwhQCyrk8EJcqB7ZxSVctTDJjdspAk2ly/z8s4dMXwT30f8VCdmlOD6G6gXCvcUvnwR2pZ8XrPh+nV0gkDgypxmgML7MYU4bIBAR0ZHbKheSCBDYS2UTEVjhrgFPYjr7x266rmubin1JDcRAxHj6lRa+cXDvvWPPfjw6/P5fQH1wwtpcXBFIQqNlJKGlo2xGDPDSeZWCLEMCeKYlH5A7LWVBrw99qVWzX1ZdkfkAhFxhZmaIgIp5b4WJGv32As51j2QmGL0xO6bzDEUUbCI1aN9Z5bdhQmN9t/8DMK+fFEcQl8gsLaLKcLzfG/OtCtwkLqRTKr/OUnhYRbA4qC9OXVc9gYyXc5uwN0ESWmbZ4HriPmFUQjpDjCA=
conda_forge_output_validation: true
